// examples/vue-example/src/components/EncryptionDemo.vue
<script setup lang="ts">
import { ref } from 'vue'
import { createFHEVM } from '@astral/fhevm-sdk'

const value = ref('')
const encrypted = ref('')
const encrypting = ref(false)
const error = ref('')

async function handleEncrypt() {
  if (!value.value) return
  
  encrypting.value = true
  error.value = ''
  
  try {
    const fhevm = await createFHEVM({ chainId: 11155111 })
    const result = await fhevm.encrypt.uint8(parseInt(value.value))
    encrypted.value = Buffer.from(result).toString('hex').substring(0, 32) + '...'
  } catch (err: any) {
    error.value = err.message || 'Encryption failed'
    console.error('Encryption failed:', err)
  } finally {
    encrypting.value = false
  }
}
</script>

<template>
  <div class="card">
    <h2>Encryption Demo</h2>
    <div class="demo-content">
      <input
        v-model="value"
        type="number"
        placeholder="Enter a number (0-255)"
        :disabled="encrypting"
      />
      
      <button
        @click="handleEncrypt"
        :disabled="encrypting || !value"
      >
        {{ encrypting ? 'Encrypting...' : 'Encrypt Value' }}
      </button>
      
      <div v-if="encrypted" class="result success">
        <p class="label">Encrypted:</p>
        <p class="value">{{ encrypted }}</p>
      </div>
      
      <div v-if="error" class="result error">
        <p>{{ error }}</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
h2 {
  margin-bottom: 1.5rem;
  color: white;
  font-size: 1.5rem;
}

.demo-content {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.result {
  padding: 1rem;
  border-radius: 0.5rem;
  text-align: left;
}

.result.success {
  background: rgba(34, 197, 94, 0.2);
  border: 1px solid rgba(34, 197, 94, 0.4);
}

.result.error {
  background: rgba(239, 68, 68, 0.2);
  border: 1px solid rgba(239, 68, 68, 0.4);
}

.label {
  font-size: 0.875rem;
  color: rgba(255, 255, 255, 0.7);
  margin-bottom: 0.5rem;
}

.value {
  font-family: monospace;
  font-size: 0.75rem;
  color: #86efac;
  word-break: break-all;
}
</style>

// templates/nextjs/src/components/fhe/EncryptionDemo.tsx
'use client';

import { useState } from 'react';
import { useEncrypt, useFHEVM } from '@astral/fhevm-sdk/react';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';
import { Input } from '../ui/Input';

export default function EncryptionDemo() {
  const fhevm = useFHEVM();
  const { encrypt, encrypting, error } = useEncrypt();
  const [value, setValue] = useState('');
  const [encrypted, setEncrypted] = useState<string>('');

  const handleEncrypt = async () => {
    try {
      const result = await fhevm.encrypt.uint8(parseInt(value));
      setEncrypted(Buffer.from(result).toString('hex').substring(0, 32) + '...');
    } catch (err) {
      console.error('Encryption failed:', err);
    }
  };

  return (
    <Card title="Encryption Demo">
      <div className="space-y-4">
        <Input
          type="number"
          value={value}
          onChange={(e) => setValue(e.target.value)}
          placeholder="Enter a number (0-255)"
        />
        <Button
          onClick={handleEncrypt}
          disabled={encrypting || !value}
          loading={encrypting}
        >
          {encrypting ? 'Encrypting...' : 'Encrypt Value'}
        </Button>
        {encrypted && (
          <div className="p-4 bg-gray-800 rounded-lg">
            <p className="text-sm text-gray-300">Encrypted:</p>
            <p className="text-xs text-green-400 font-mono break-all">{encrypted}</p>
          </div>
        )}
        {error && (
          <div className="p-4 bg-red-900/50 rounded-lg">
            <p className="text-sm text-red-300">{error.message}</p>
          </div>
        )}
      </div>
    </Card>
  );
}
